### ISSUE TITLE
gendocs

### ISSUE THREAD

**Issue by tomsmeding** [tomsmeding/aimaker#12]
Currently the markdown generated is not really markdown.

![screen shot 2015-08-04 at 08 45 52](https://cloud.githubusercontent.com/assets/6559933/9054811/532d49f8-3a85-11e5-9087-3ee2ef9f2915.png)

I love the text generator tho

**Comment by tomsmeding** [comment]
Also:

```
"content": "All variables starting with `_` are immutable, which means you can't create variables whose name starts with an `_`."
```

Produces:

```
-------------------------------------------------
All variables starting with `_` are
immutable, which means you can't create variables
whose name starts with an `_`.
-------------------------------------------------
```

(second line is 49 chars long, while the limit is at 45...)

and not the expected:

```
---------------------------------------------
All variables starting with `_` are
immutable, which means you can't create
variables whose name starts with an `_`.
---------------------------------------------
```

**Comment by tomsmeding** [comment]
(Text above is of commit a4cd53e) (kind of)

**Comment by lieuwex** [comment]
@tomsmeding yup, still have to commit the stringbuilder changes, will in a min

**Comment by lieuwex** [comment]
@tomsmeding the line length limiting is fixed in 160bf58968e981067e93d15bcb0384330d131948

**Comment by tomsmeding** [comment]
:+1:

**Comment by lieuwex** [comment]
0c8544402a432638b31b5fb9b4fb06a1314ed348
![](http://i.imgur.com/BhuKdfs.png)

**Comment by tomsmeding** [comment]
:+1:
