### ISSUE TITLE
Bot tiers

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/aimaker#4]
@tomsmeding what did you have in mind, exactly?

**Comment by tomsmeding** [comment]
`build` now takes no arguments. Let it take one argument, `level`.
This `level` argument has three possible values, `0`, `1` and `2`:
- `0`: The new bot is only able to move around (`move`, `rot` etc.)
- `1`: The new bot has communication skills (`trans`, `translocal`, etc.) (could maybe be split up if we add other communication channels besides `trans`)
- `2`: The new bot is fully functional and can even `build`.

**Comment by lieuwex** [comment]
Alright, sounds good.
We need to store the minimal tier per instruciton somewhere, like a function in `parameters.cpp`?

**Comment by tomsmeding** [comment]
Sounds alright. Making it a function might be overkil (could also be just data, a map&lt;Parser::Instruction,bool&gt; or something), but it is also more flexible.

**Comment by lieuwex** [comment]
#5
